version: '3'
services:
  api:
    build: 
      context: ./todo-api
      dockerfile: Dockerfile.prod
  web:
    build: 
      context: ./todo-ui
      dockerfile: Dockerfile.prod
  auth:
    build: 
      context: ./todo-auth
      dockerfile: Dockerfile.prod
  migrator:
    build: ./todo-db