version: '3'
services:
  web:
    build: ./todo-api
    depends_on:
      - db
    environment:
      - HttpsRedirectionDisabled
    ports:
      - 80:80
  migrator:
    build: ./todo-db
    depends_on:
      - db
    environment:
    - database__server=db
    - database__name=todo
    - database__user=sa
    - database__password=1nter@dmin
    restart: on-failure
  db:
    image: "microsoft/mssql-server-linux"
    ports:
    - 1433:1433
    environment:
    - ACCEPT_EULA=Y
    - SA_PASSWORD=1nter@dmin