version: '3'
services:
  web:
    build: ./todo-api
    depends_on:
      - db
    environment:
      - server__HttpsRedirectionDisabled=True   
      - database__server=db
      - database__name=todo
      - database__user=sa
      - database__password=P@ssword1
    ports:
      - 80:80
  migrator:
    build: ./todo-db
    depends_on:
      - db
    environment:
    - database__server=db
    - database__name=todo
    - database__user=sa
    - database__password=P@ssword1
    restart: on-failure
  db:
    image: "microsoft/mssql-server-linux"
    ports:
    - 1433:1433
    environment:
    - ACCEPT_EULA=Y
    - SA_PASSWORD=P@ssword1