version: '3'
services:
  web:
    build: ./todo-ui
    depends_on:
      - api
    ports: 
      - 4200:4200
      - 49153:49153
    volumes:
      - ./todo-ui:/app
    working_dir: /app
    entrypoint: ng serve --host 0.0.0.0
  api:
    build: ./todo-api
    depends_on:
      - db
      - auth
    environment:
      - server__HttpsRedirectionDisabled=False   
      - database__server=db
      - database__name=todo
      - database__user=sa
      - database__password=P@ssword1
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5001:5001
    volumes:
      - ./todo-api:/app
    working_dir: /app
    entrypoint: dotnet watch run
  auth:
    build: ./todo-auth
    depends_on:
      - db
    ports:
      - 5000:5000
    volumes:
      - ./todo-auth:/app
    working_dir: /app
    environment:    
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_ENVIRONMENT=Development
      - IDENTITY_ISSUER="http://auth:5000"
    entrypoint: dotnet watch run
  jobdashboard:
    build: ./todo-jobdashboard
    depends_on:
      - db
    environment:
      - hangfire__server=db
      - hangfire__name=todo
      - hangfire__user=sa
      - hangfire__password=P@ssword1
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 6001:6001
  migrator:
    build: ./todo-db
    depends_on:
      - db
    environment:
    - database__server=db
    - database__name=todo
    - database__user=sa
    - database__password=P@ssword1
    restart: on-failure
  db:
    image: "microsoft/mssql-server-linux"
    #logging:
      #driver: none
    ports:
    - 1433:1433
    environment:
    - ACCEPT_EULA=Y
    - SA_PASSWORD=P@ssword1