FROM microsoft/dotnet:2.1-sdk as build

COPY ./todo-auth.csproj /src/todo-auth.csproj
RUN dotnet restore /src/todo-auth.csproj
RUN mkdir /out

COPY . /src

RUN dotnet publish /src --output /out

FROM microsoft/dotnet:2.1-aspnetcore-runtime-alpine AS runtime

COPY --from=build /out /app

WORKDIR /app
EXPOSE 443
EXPOSE 80
ENTRYPOINT ["dotnet", "todo-auth.dll" ]